import { createLocaleView } from '../locales/view.ts'

/** Dynamic board vocabulary; template leaves are interpolated by `formatTemplate`. */
export const BOARD_STRINGS = createLocaleView({
  status: {
    working: 'board.status.working',
    waiting: 'board.status.waiting',
    idle: 'board.status.idle',
    dead: 'board.status.dead',
    unknown: 'board.status.unknown',
  },
  attention: {
    gap: 'board.attention.gap',
  },
  daemon: {
    probe: 'board.daemon.probe',
    adopted: 'board.daemon.adopted',
    defer: 'board.daemon.defer',
    reprobe: 'board.daemon.reprobe',
    hosting: 'board.daemon.hosting',
    hosted: 'board.daemon.hosted',
    backoff: 'board.daemon.backoff',
    failed: 'board.daemon.failed',
  },
  stream: {
    ok: 'board.stream.ok',
    degraded: 'board.stream.degraded',
    unknown: 'board.stream.unknown',
  },
  banner: {
    daemonFailed: 'board.banner.daemonFailed',
    daemonFailedSpawn: 'board.banner.daemonFailedSpawn',
    daemonFailedExit: 'board.banner.daemonFailedExit',
    daemonFailedTimeout: 'board.banner.daemonFailedTimeout',
    daemonStale: 'board.banner.daemonStale',
    daemonStaleCode: 'board.banner.daemonStaleCode',
    streamDegraded: 'board.banner.streamDegraded',
  },
  empty: {
    daemonFailedTitle: 'board.empty.daemonFailedTitle',
    daemonFailedHint: 'board.empty.daemonFailedHint',
    daemonDeferTitle: 'board.empty.daemonDeferTitle',
    daemonDeferHint: 'board.empty.daemonDeferHint',
    filteredTitle: 'board.empty.filteredTitle',
    filteredHint: 'board.empty.filteredHint',
    noSessionsTitle: 'board.empty.noSessionsTitle',
    noSessionsHint: 'board.empty.noSessionsHint',
  },
  topbar: {
    title: 'board.topbar.title',
    refresh: 'board.topbar.refresh',
    refreshing: 'board.topbar.refreshing',
    refreshTitle: 'board.topbar.refreshTitle',
    refreshFailed: 'board.topbar.refreshFailed',
    dismiss: 'board.topbar.dismiss',
    showDead: 'board.topbar.showDead',
    collapseIdle: 'board.topbar.collapseIdle',
    collapseIdleTitle: 'board.topbar.collapseIdleTitle',
    analyzeCrossAgent: 'board.topbar.analyzeCrossAgent',
    cluster: 'board.topbar.cluster',
    timeWindow: 'board.topbar.timeWindow',
    countWorking: 'board.topbar.countWorking',
    countWaiting: 'board.topbar.countWaiting',
    countTotal: 'board.topbar.countTotal',
    filterByStatusTitle: 'board.topbar.filterByStatusTitle',
    clearStatusFilterTitle: 'board.topbar.clearStatusFilterTitle',
  },
  group: {
    collapseTitle: 'board.group.collapseTitle',
    expandTitle: 'board.group.expandTitle',
    showAll: 'board.group.showAll',
    showLess: 'board.group.showLess',
    idleSummary: 'board.group.idleSummary',
    expandIdle: 'board.group.expandIdle',
    collapseIdle: 'board.group.collapseIdle',
  },
  card: {
    noEvent: 'board.card.noEvent',
    untitled: 'board.card.untitled',
    observedDisclaimer: 'board.card.observedDisclaimer',
    observedValue: 'board.card.observedValue',
    lastReconcile: 'board.card.lastReconcile',
    neverReconciled: 'board.card.neverReconciled',
    copyId: 'board.card.copyId',
    copied: 'board.card.copied',
  },
  time: {
    justNow: 'board.time.justNow',
    minutesAgo: 'board.time.minutesAgo',
    hoursAgo: 'board.time.hoursAgo',
  },
  timeWindow: {
    hours: 'board.timeWindow.hours',
    days: 'board.timeWindow.days',
  },
  groupCount: 'board.groupCount',
  unknownProject: 'board.unknownProject',
  cluster: {
    title: 'board.cluster.title',
    count: 'board.cluster.count',
    empty: 'board.cluster.empty',
    sessions: 'board.cluster.sessions',
  },
  archive: {
    open: 'board.archive.open',
    openTitle: 'board.archive.openTitle',
    title: 'board.archive.title',
    explain: 'board.archive.explain',
    threshold: 'board.archive.threshold',
    threshold30m: 'board.archive.threshold30m',
    threshold2h: 'board.archive.threshold2h',
    threshold24h: 'board.archive.threshold24h',
    thresholdCustom: 'board.archive.thresholdCustom',
    customMinutes: 'board.archive.customMinutes',
    preview: 'board.archive.preview',
    previewing: 'board.archive.previewing',
    previewEmpty: 'board.archive.previewEmpty',
    previewCount: 'board.archive.previewCount',
    selectAll: 'board.archive.selectAll',
    selectNone: 'board.archive.selectNone',
    confirm: 'board.archive.confirm',
    confirming: 'board.archive.confirming',
    cancel: 'board.archive.cancel',
    done: 'board.archive.done',
    failed: 'board.archive.failed',
    previewFailed: 'board.archive.previewFailed',
    unavailable: 'board.archive.unavailable',
    dispose: 'board.archive.dispose',
    disposeHint: 'board.archive.disposeHint',
    doneDisposed: 'board.archive.doneDisposed',
    doneDisposeFailed: 'board.archive.doneDisposeFailed',
  },
  archived: {
    summary: 'board.archived.summary',
    expand: 'board.archived.expand',
    collapse: 'board.archived.collapse',
    reason: {
      manual: 'board.archived.reason.manual',
      batch: 'board.archived.reason.batch',
      auto: 'board.archived.reason.auto',
    },
    archivedAt: 'board.archived.archivedAt',
    restore: 'board.archived.restore',
    restoring: 'board.archived.restoring',
    restoreAll: 'board.archived.restoreAll',
    restoreFailed: 'board.archived.restoreFailed',
  },
  widget: {
    label: 'board.widget.label',
    connection: {
      ok: 'board.widget.connection.ok',
      degraded: 'board.widget.connection.degraded',
      off: 'board.widget.connection.off',
    },
    working: 'board.widget.working',
  },
} as const)

export type BoardStrings = typeof BOARD_STRINGS
